name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run scanners, linters and spellchecking.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source.
        uses: actions/checkout@v3
      - name: Setup pnpm.
        uses: pnpm/action-setup@v2
      - name: Setup node.
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: pnpm
      - name: Install dependencies.
        run: pnpm install
      - name: Execute audit-ci scanner.
        run: npx audit-ci
      - name: Check code format.
        run: pnpm fmt:check
      - name: Lint code-base.
        run: pnpm lint
      - name: Spellcheck code-base.
        run: pnpm spellcheck
  unit:
    name: Run Unit Tests.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [19]
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - name: Checkout source.
        uses: actions/checkout@v3
      - name: Setup pnpm.
        uses: pnpm/action-setup@v2
      - name: Setup node (${{ matrix.node-version }}).
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies.
        run: pnpm install
      - name: Run Testsuite.
        run: pnpm -r test
